# Generated by Django 4.2.6 on 2023-11-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_photo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='altText',
            field=models.TextField(blank=True, verbose_name=''),
        ),
    ]
