# Generated by Django 4.2.6 on 2023-11-26 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_app', '0005_alter_photo_alttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(related_name='photo_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='altText',
            field=models.CharField(default='User Submitted Photo', max_length=200),
        ),
    ]
