# Generated by Django 4.2.6 on 2023-11-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0007_photographer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='gallery',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_app.gallery'),
        ),
    ]
